# Generated by Django 5.0.6 on 2024-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='ebe48bc4c18c4886bca20054e947dc9d', max_length=100),
        ),
    ]
