# Generated by Django 5.0.6 on 2024-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_alter_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='8f28d5bf60844fad8353d0fae1aea38e', max_length=100, unique=True),
        ),
    ]
