# Generated by Django 5.0.6 on 2024-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_alter_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='17bc02a3d42a41d392470d308db633e2', max_length=100, unique=True),
        ),
    ]
