# Generated by Django 5.0.6 on 2024-06-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0025_alter_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='25c52d78d9ce4310969dc540f59d24ae', max_length=100, unique=True),
        ),
    ]
