# Generated by Django 5.0.6 on 2024-06-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0026_alter_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderesult',
            name='request_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='4d0e9e4ebb3e4507af28176ac61c255d', max_length=100, unique=True),
        ),
    ]
