# Generated by Django 5.0.6 on 2024-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='1660050b46a8441390b564d3ef695c57', max_length=100, unique=True),
        ),
    ]
