# Generated by Django 5.0.6 on 2024-05-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_alter_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='1d1d140d0ee34c6181c3638f6595b828', max_length=100, unique=True),
        ),
    ]
