# Generated by Django 5.0.6 on 2024-05-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_remove_coderesult_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='eb145e40289a4bc689161f22948b405e', max_length=100, unique=True),
        ),
    ]
