# Generated by Django 5.0.6 on 2024-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_alter_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='f26ead3072364706b8c22845bec78414', max_length=100, unique=True),
        ),
    ]
