# Generated by Django 5.0.6 on 2024-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_alter_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='7f9d75359839428f968b0eaace749abf', max_length=100, unique=True),
        ),
    ]
