# Generated by Django 5.0.6 on 2024-05-25 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_alter_submission_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'code_submissions',
            },
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('status', models.CharField(max_length=50)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'execution_results',
            },
        ),
        migrations.DeleteModel(
            name='CodeResult',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
