# Generated by Django 5.0.6 on 2024-05-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_codesubmission_executionresult_delete_coderesult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default='b5894897e9c6456ba56e8e32d00b17f2', max_length=100, unique=True)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CodeSubmission',
        ),
        migrations.DeleteModel(
            name='ExecutionResult',
        ),
    ]
