# Generated by Django 5.0.6 on 2024-05-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_coderesult_submission_delete_codesubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='0e0d43353498422f81aa6cbec8be54e7', max_length=100, unique=True),
        ),
    ]
