# Generated by Django 5.0.6 on 2024-05-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0023_alter_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='dbb857b279e44cc4aaaad7f17dcdb282', max_length=100, unique=True),
        ),
    ]
