# Generated by Django 5.0.6 on 2024-06-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0027_alter_coderesult_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='ca521ab0a3cd48b7b07b06acc457bf8f', max_length=100, unique=True),
        ),
    ]
