# Generated by Django 5.0.6 on 2024-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0028_alter_submission_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderesult',
            name='request_id',
            field=models.CharField(default='d9f6551e9cb64135806502ed5fe3b8e7', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='014714a8e8354348ab60422ef294f23d', max_length=100, unique=True),
        ),
    ]
