# Generated by Django 5.0.6 on 2024-06-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0029_alter_coderesult_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderesult',
            name='request_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='request_id',
            field=models.CharField(default='75c97aaef1da463b8244a897be80264e', max_length=100, unique=True),
        ),
    ]
